### ISSUE TITLE
Outdated CMD package (some commands doesn't work with the latest atlas v0.14.1 version)

### ISSUE THREAD

**Issue by fernandobandeira** [ariga/atlas#2135]
When running atlas with the latest packages available:

```
ariga.io/atlas v0.14.1
ariga.io/atlas/cmd/atlas v0.13.1
```

The command `go run ariga.io/atlas/cmd/atlas migrate hash`

Returns an error:
```
../../../go/pkg/mod/ariga.io/atlas/cmd/atlas@v0.13.1/internal/cmdapi/migrate.go:91:31: undefined: migrate.WithFromVersion
```

**Comment by a8m** [comment]
Hey @fernandobandeira 👋🏻

Thanks for reporting this. I will update the cmd/atlas module - we just don’t maintain it that often.

To unblock yourself, check out the standard installation step: https://atlasgo.io/getting-started#installation

```sh
curl -sSf https://atlasgo.sh | sh
```

**Comment by vdobler** [comment]
The problem exists still on v0.15.0 too.
As we use the "tools.go trick" to version tooling we need a go get/install-able cmd/atlas

Is there a special reason to have it on a different lifecycle at all?

**Comment by aimuz** [comment]
The latest version is now 0.22.0, while cli is still 0.13.1.

**Comment by a8m** [comment]
Hey! You can use the following command to install Atlas:

```
curl -sSf https://atlasgo.sh | sh
```

Regarding Go installation: We no longer maintain the `cmd/atlas` package as an executable - mainly for technical and time reasons. Atlas is used by various programming languages, like Python and Java, and the binary we distribute includes additional capabilities.

> This is a major inconvenience for us without any obvious underlying technical reason.

Our cmd/atlas package uses [`replace`](https://github.com/ariga/atlas/blob/master/cmd/atlas/go.mod#L5) to avoid adding all `cmd/atlas` dependencies for projects that use the root package - `ariga.io/atlas` (e.g., entgo.io). There's no way to `go get` such packages - we previously used `go.work` for this purpose, but it introduced different pains, and I decided to remove it.
